config:
  data: YAML #Either "DATABASE" or "YAML"
  database:
    host: localhost # host of your database
    port: 3306 # default port for MariaDB and MySQL
    database: db # name of your database. A database server can contain multiple databases
    user: username
    password: pass

  interests:
    enabled: true
    interest-time: 31 # in hours

  use-anvil-instead-sign: false

  messages:
    deposit: "&aDeposited &6%money% coins&a! There's now &6%bank_balance% coins &ain the account!"
    withdraw: "&aWithdrew &6%money% coins&a! There's now &6%bank_balance% coins &ain the account!"
    max-coins: "&cYou already have the maximum amount of Coins in your bank!"
    deposit-little-amount: "&cYou cannot deposit this little amount"
    withdraw-little-amount: "&cYou cannot withdraw this little amount"
    interest: "&aYou have just received &6%money% &aas interest in your personal bank account!"
