name: MortisBank
version: '2.1'
main: me.none030.mortisbank.MortisBank
api-version: 1.13
depend:
  - Vault
softdepend:
  - ProtocolLib
  - Essentials
  - PlaceholderAPI
commands:
  bank:
    aliases:
      - mortisbank